### ISSUE TITLE
Assert log.dirs Property not Misconfigured

### ISSUE THREAD

**Issue by tommy04062019** [confluentinc/cp-ansible#1240]
**For Confluent Enterprise Support customers, we would strongly advise you to open a Support ticket which will be addressed within your Support contract SLA at ```https://support.confluent.io```**

**Describe the issue**
Something wrong with task `Assert log.dirs Property not Misconfigured`. The error show `'dict object' has no attribute 'name'`. It seems that error come from `kafka_broker_properties`. In my configuration, I use `kafka_broker_custom_properties`. It's normal when debug printing but failed with `kafka_broker_properties` (default, I dont set this one in my config)

**To Reproduce**
Steps to reproduce the behaviour:

**Expected behaviour**

**Inventory File**
Please provide your inventory file in order to aid in the investigation.

**Logs**
[failure.txt](https://github.com/confluentinc/cp-ansible/files/9988469/failure.txt)

**Environment (please complete the following information):**
 - OS: Ubuntu20.04
 - CP-Ansible Branch: 7.3.x
 - Ansible Version: ansible 2.13.2

**Additional context**

**Comment by tommy04062019** [comment]
The above config works well with CP-Ansible: 7.0.x. It seems similiar to ticket 1183. Somehow have conflict between group level and host level setting, I have to remove `kafka_broker_custom_listeners` in the setting of each host. It works now. So, the question is where I can set `kafka_broker_custom_listeners` for each host in case a host have multiple ip address and I want to set  listener on a specific ip?
